name: download

on:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    download:
        runs-on: ubuntu-latest

        steps:

            - name: Check out repo
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install uk-covid19

            - name: Run download script
              run: |
                  set -x
                  ls -la . data/
                  echo "CSV_FILENAME=$(./download.py)" >> $GITHUB_ENV
                  ls -la . data/

            - name: Commit resulting CSV file to repository
              run: |
                  set -x
                  ls -la . data/
                  git config user.name msleigh
                  git config user.email msleigh@users.noreply.github.com
                  git add -v ./*.csv
                  git commit -vvm"Updates archive with ${CSV_FILENAME}" || exit 0
                  git push -v origin main
