name: download

on:
    workflow_dispatch:
    schedule:
        - cron: '00 * * * *'

jobs:
    download:
        runs-on: ubuntu-latest

        steps:

            - name: Check out repo
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install uk-covid19

            - name: Run download script
              run:
                  ./download.py

            - name: Commit resulting CSV file to repository
              run: |
                  git config user.name msleigh
                  git config user.email msleigh@users.noreply.github.com
                  git add -v ./*.csv
                  git commit -vvm"Updates archive" || exit 0
                  git push -v origin master
